/*
 * CMConstantGlue.h
 * /Applications/Camino.app
 * osaglue 0.5.1
 *
 */

#import <Foundation/Foundation.h>
#import "Appscript/Appscript.h"

@interface CMConstant : ASConstant
+ (id)constantWithCode:(OSType)code_;

/* Enumerators */

+ (CMConstant *)applicationResponses;
+ (CMConstant *)ask;
+ (CMConstant *)case_;
+ (CMConstant *)diacriticals;
+ (CMConstant *)expansion;
+ (CMConstant *)hyphens;
+ (CMConstant *)no;
+ (CMConstant *)numericStrings;
+ (CMConstant *)punctuation;
+ (CMConstant *)whitespace;
+ (CMConstant *)yes;

/* Types and properties */

+ (CMConstant *)April;
+ (CMConstant *)August;
+ (CMConstant *)December;
+ (CMConstant *)EPSPicture;
+ (CMConstant *)February;
+ (CMConstant *)Friday;
+ (CMConstant *)GIFPicture;
+ (CMConstant *)JPEGPicture;
+ (CMConstant *)January;
+ (CMConstant *)July;
+ (CMConstant *)June;
+ (CMConstant *)March;
+ (CMConstant *)May;
+ (CMConstant *)Monday;
+ (CMConstant *)November;
+ (CMConstant *)October;
+ (CMConstant *)PICTPicture;
+ (CMConstant *)RGB16Color;
+ (CMConstant *)RGB96Color;
+ (CMConstant *)RGBColor;
+ (CMConstant *)Saturday;
+ (CMConstant *)September;
+ (CMConstant *)Sunday;
+ (CMConstant *)TIFFPicture;
+ (CMConstant *)Thursday;
+ (CMConstant *)Tuesday;
+ (CMConstant *)URL;
+ (CMConstant *)Wednesday;
+ (CMConstant *)addressBookCollection;
+ (CMConstant *)alias;
+ (CMConstant *)anything;
+ (CMConstant *)application;
+ (CMConstant *)applicationBundleID;
+ (CMConstant *)applicationSignature;
+ (CMConstant *)applicationURL;
+ (CMConstant *)best;
+ (CMConstant *)bonjourCollection;
+ (CMConstant *)bookmark;
+ (CMConstant *)bookmarkBarCollection;
+ (CMConstant *)bookmarkFolder;
+ (CMConstant *)bookmarkItem;
+ (CMConstant *)bookmarkMenuCollection;
+ (CMConstant *)boolean;
+ (CMConstant *)boundingRectangle;
+ (CMConstant *)bounds;
+ (CMConstant *)browserWindow;
+ (CMConstant *)centimeters;
+ (CMConstant *)classInfo;
+ (CMConstant *)class_;
+ (CMConstant *)closeable;
+ (CMConstant *)colorTable;
+ (CMConstant *)cubicCentimeters;
+ (CMConstant *)cubicFeet;
+ (CMConstant *)cubicInches;
+ (CMConstant *)cubicMeters;
+ (CMConstant *)cubicYards;
+ (CMConstant *)currentTab;
+ (CMConstant *)dashStyle;
+ (CMConstant *)data;
+ (CMConstant *)date;
+ (CMConstant *)decimalStruct;
+ (CMConstant *)degreesCelsius;
+ (CMConstant *)degreesFahrenheit;
+ (CMConstant *)degreesKelvin;
+ (CMConstant *)description_;
+ (CMConstant *)doubleInteger;
+ (CMConstant *)elementInfo;
+ (CMConstant *)encodedString;
+ (CMConstant *)enumerator;
+ (CMConstant *)eventInfo;
+ (CMConstant *)extendedFloat;
+ (CMConstant *)feet;
+ (CMConstant *)fileRef;
+ (CMConstant *)fileSpecification;
+ (CMConstant *)fileURL;
+ (CMConstant *)fixed;
+ (CMConstant *)fixedPoint;
+ (CMConstant *)fixedRectangle;
+ (CMConstant *)float128bit;
+ (CMConstant *)float_;
+ (CMConstant *)floating;
+ (CMConstant *)frontmost;
+ (CMConstant *)gallons;
+ (CMConstant *)grams;
+ (CMConstant *)graphicText;
+ (CMConstant *)id_;
+ (CMConstant *)inches;
+ (CMConstant *)index;
+ (CMConstant *)integer;
+ (CMConstant *)internationalText;
+ (CMConstant *)internationalWritingCode;
+ (CMConstant *)item;
+ (CMConstant *)kernelProcessID;
+ (CMConstant *)kilograms;
+ (CMConstant *)kilometers;
+ (CMConstant *)lastVisitDate;
+ (CMConstant *)list;
+ (CMConstant *)liters;
+ (CMConstant *)locationReference;
+ (CMConstant *)longFixed;
+ (CMConstant *)longFixedPoint;
+ (CMConstant *)longFixedRectangle;
+ (CMConstant *)longPoint;
+ (CMConstant *)longRectangle;
+ (CMConstant *)machPort;
+ (CMConstant *)machine;
+ (CMConstant *)machineLocation;
+ (CMConstant *)meters;
+ (CMConstant *)miles;
+ (CMConstant *)miniaturizable;
+ (CMConstant *)miniaturized;
+ (CMConstant *)missingValue;
+ (CMConstant *)modal;
+ (CMConstant *)name;
+ (CMConstant *)null;
+ (CMConstant *)ounces;
+ (CMConstant *)parameterInfo;
+ (CMConstant *)pixelMapRecord;
+ (CMConstant *)point;
+ (CMConstant *)pounds;
+ (CMConstant *)processSerialNumber;
+ (CMConstant *)properties;
+ (CMConstant *)property;
+ (CMConstant *)propertyInfo;
+ (CMConstant *)quarts;
+ (CMConstant *)record;
+ (CMConstant *)reference;
+ (CMConstant *)resizable;
+ (CMConstant *)rotation;
+ (CMConstant *)script;
+ (CMConstant *)selectedSource;
+ (CMConstant *)selectedText;
+ (CMConstant *)shortFloat;
+ (CMConstant *)shortInteger;
+ (CMConstant *)shortcut;
+ (CMConstant *)source;
+ (CMConstant *)squareFeet;
+ (CMConstant *)squareKilometers;
+ (CMConstant *)squareMeters;
+ (CMConstant *)squareMiles;
+ (CMConstant *)squareYards;
+ (CMConstant *)string;
+ (CMConstant *)styledClipboardText;
+ (CMConstant *)styledText;
+ (CMConstant *)suiteInfo;
+ (CMConstant *)tab;
+ (CMConstant *)text;
+ (CMConstant *)textStyleInfo;
+ (CMConstant *)title;
+ (CMConstant *)titled;
+ (CMConstant *)topTenCollection;
+ (CMConstant *)typeClass;
+ (CMConstant *)unicodeText;
+ (CMConstant *)unsignedInteger;
+ (CMConstant *)utf16Text;
+ (CMConstant *)utf8Text;
+ (CMConstant *)version;
+ (CMConstant *)version_;
+ (CMConstant *)visible;
+ (CMConstant *)visitCount;
+ (CMConstant *)window;
+ (CMConstant *)writingCode;
+ (CMConstant *)yards;
+ (CMConstant *)zoomable;
+ (CMConstant *)zoomed;
@end

